//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CUSTFYPEntities1 : DbContext
    {
        public CUSTFYPEntities1()
            : base("name=CUSTFYPEntities1")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artefact> Artefacts { get; set; }
        public virtual DbSet<Assessment> Assessments { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<InstructorProject> InstructorProjects { get; set; }
        public virtual DbSet<ProjectExam> ProjectExams { get; set; }
        public virtual DbSet<Statement> Statements { get; set; }
        public virtual DbSet<PLO> PLOes { get; set; }
        public virtual DbSet<CLO> CLOes { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Panel> Panels { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Mark> Marks { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
    }
}
