
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication6.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Group
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Group()
    {

        this.Projects = new HashSet<Project>();

    }


    public int Id { get; set; }

    public string gName { get; set; }

    public int TermId { get; set; }

    public string StudentId1 { get; set; }

    public string StudentId2 { get; set; }

    public string StudentId3 { get; set; }

    public string IsActive { get; set; }

    public Nullable<int> PanelId { get; set; }



    public virtual Panel Panel { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Project> Projects { get; set; }

    public virtual Term Term { get; set; }

}

}
